### ISSUE TITLE
Request for F16 quant level

### ISSUE THREAD

**Issue by YarvixPA** [rainlizard/EasyQuantizationGUI#1]
@rainlizard  Good easy way to quant models, Thanks for make it.

It's possible to add save the model in F16?

**Comment by rainlizard** [comment]
Hi, I've added the option for F16: https://github.com/rainlizard/EasyQuantizationGUI/releases

I also updated the `llama-quantize.exe` and associated .dll files to use the latest files from [here](https://github.com/city96/ComfyUI-GGUF/tree/main/tools). (they'll soon fall out of date again, that's a flaw of this GUI)

**Comment by YarvixPA** [comment]
> Hi, I've added the option for F16: https://github.com/rainlizard/EasyQuantizationGUI/releases
> 
> 
> 
> I also updated the `llama-quantize.exe` and associated .dll files to use the latest files from [here](https://github.com/city96/ComfyUI-GGUF/tree/main/tools). (they'll soon fall out of date again, that's a flaw of this GUI)

Yes, thank for added F16 🔝💯. It's there a way to chat with you on Discord?

**Comment by rainlizard** [comment]
my discord ID is `rainlizard`, however there probably won't be anything more to say.
